# Generated by Django 4.2.7 on 2023-12-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advert_title', models.CharField(max_length=1000)),
                ('advert_img', models.ImageField(upload_to='static/adverts/')),
            ],
        ),
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('user_email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('Phone_no', models.CharField(max_length=100)),
                ('email_subject', models.CharField(max_length=100)),
                ('email_message', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='CoursesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=100)),
                ('course_description', models.TextField(max_length=1000)),
                ('course_img', models.ImageField(upload_to='static/images/')),
                ('course_requirements', models.CharField(max_length=200)),
                ('course_duration', models.CharField(max_length=100)),
                ('course_cost', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
