# Generated by Django 4.2.4 on 2023-11-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoursesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=20)),
                ('course_description', models.CharField(max_length=1000)),
                ('course_img', models.ImageField(upload_to='static/course_images/')),
                ('course_requirements', models.CharField(max_length=200)),
                ('course_duration', models.CharField(max_length=10)),
            ],
        ),
    ]
